# Generated by Django 5.0.1 on 2024-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_alter_fileversion_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(),
        ),
    ]
