# Generated by Django 5.0.1 on 2024-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0007_alter_fileversion_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="file_name",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="url",
            field=models.CharField(default="/", max_length=2048),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
