# Generated by Django 5.0.1 on 2024-04-11 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0008_alter_fileversion_file_name_alter_fileversion_url_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
