# Generated by Django 5.0.1 on 2024-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0011_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="relative_url",
            field=models.CharField(default="/", max_length=2048),
        ),
    ]
